### ISSUE TITLE
ARMCLANG missing in CMSIS-PACK spec ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/Open-CMSIS-Pack#55]
[https://open-cmsis-pack.github.io/Open-CMSIS-Pack/main/html/pdsc_conditions_pg.html#CompilerEnumType](https://open-cmsis-pack.github.io/Open-CMSIS-Pack/main/html/pdsc_conditions_pg.html#CompilerEnumType)

indicates ARMCC (compiler 5) but not ARMCLANG (compiler 6)

**Comment by jkrech** [comment]
If you scroll up a bit on the same page you see the attribute Toptions
```
Tcompiler="ARMCC" Toptions="AC6"
```

**Comment by fred-r** [comment]
Perfect, thanks !
